### ISSUE TITLE
ability to customize pie menu?

### ISSUE THREAD

**Issue by slrgt** [bastianlstrube/ContextPie#8]
Will it be possible for users to customize the pie menu? Love this addon but I would like to make it look like this when opening the pie menu in object mode

![blender_fqb12sspsZ](https://github.com/user-attachments/assets/b4be15db-cf41-4589-8462-047351553676)

**Comment by bastianlstrube** [comment]
Not from any settings or preferences. Making an editor is beyond what I have time for :) 
But since you have a github account, I assume you would be up for the challenge of doing a fork? I'll be happy to show you how to do it in the python file.
The four options in your picture is the four lines of code [here](https://github.com/bastianlstrube/ContextPie/blob/main/PIE_mode.py#L153).
Changing the order of options is just swapping a few lines of python around. 

The menu on the side with icons might be a little more involved but I can probably point you in a direction of other extensions you can borrow from.

**Comment by slrgt** [comment]
Ok i can try this
